# Generated by Django 5.1.2 on 2026-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_seed_league_season"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "league_id",
                    models.IntegerField(
                        blank=True,
                        help_text="API league id",
                        null=True,
                    ),
                ),
                (
                    "season_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Season year as used by the API (e.g. 2025).",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Trigger source, e.g. admin_button, mgmt_cmd, api_refresh, cli.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PARTIAL_SUCCESS", "Partial success"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("error_summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["league_id", "season_year", "started_at"],
                        name="data_pipeli_league__a3e6cc_idx",
                    ),
                ],
            },
        ),
    ]
