# Generated by Django 5.1.2 on 2026-05-23 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="learningdocument",
            name="author",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="learningdocument",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="learningdocument",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("", "—"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="learningdocument",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("es", "Spanish"), ("en", "English"), ("", "—")],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="learningdocument",
            name="thumbnail_key",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="learningdocument",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="LearningTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="learningdocument",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents",
                to="learning.learningtag",
            ),
        ),
        migrations.CreateModel(
            name="LearningActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_page", models.PositiveIntegerField(blank=True, null=True)),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="learning.learningdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_viewed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "document"),
                        name="learning_unique_activity_per_user_doc",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningStarred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_by",
                        to="learning.learningdocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_starred",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "document"),
                        name="learning_unique_starred_per_user_doc",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="learningtag",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"),
                name="learning_unique_tag_slug_per_owner",
            ),
        ),
    ]
