# dbt-duckdb project for football fixtures. Sources from pipeline-loaded DuckDB.

name: "football"
version: "1.0.0"
config-version: 2
profile: "football"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  is_dev_run: true
